server:
  port: 443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-alias: mycert
    key-store-type: JKS

spring:
  application:
    name: fees-management-app
  data:
    mongodb:
      uri: mongodb+srv://adminUserForBloodDonation:3aGHgnENkiNbj0r4@maincluster.ugy53li.mongodb.net/FeesManagementSystem

payment:
  mailbody: Hello, @StudentName,Payment of Rs.@Amount received for the month of @Month
  mailsubject:  Payment Received for the Month @Month

